// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xngitycoruaywfjfmgjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuZ2l0eWNvcnVheXdmamZtZ2p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDc5MzcsImV4cCI6MjA2NDUyMzkzN30.dnf0DYkePT3hT3Q66P36xVogqEJ9aJxi4lhAQ3y74S0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);